### ISSUE TITLE
ThemeEditor should save theme settings via cookie or be given the ability to upload existing themes made by this site

### ISSUE THREAD

**Issue by rakosi2** [Gibbu/Website#2]
Once I made the theme, I can not make any modifications to it and have to redo all of the modifications which is a big pain. Please allow some sort of theme saving system so I can make modifications.

**Comment by Gibbu** [comment]
While they sound nice, they're both pretty tricky to do with the current site. I'm working on a complete rewrite (again). Importing existing files will be a priority.
